### PR TITLE
Fix palette layout

### PR DESCRIPTION
**Pull request by fritzmg**
Before:

image

After:

image

### CODE REVIEW

**Comment by aschempp** [comment]
feels like this is actually intended 😅 but maybe we should place the two input fields next to each other and the checkboxes after them?

**Comment by fritzmg** [comment]
hm, idk, you'll need to decide that ;). If this was really intended then you might as well leave it as is - though I don't think Contao's layout actually intended this to be used this way.

**Comment by aschempp** [comment]
Yes it is, thats exactly what `m12` is for? If you have only one checkbox next to a field, you need `m12`. If you want two, don't use `m12`. Otherwise checkboxes could always have `m12` 😅 

But maybe @leo @Toflar can shed their opinion?

**Comment by fritzmg** [comment]
The Contao Core uses `m12` whenever a checkbox is to the left or right of a regular `text` input field. If two checkboxes are besides each other, you do not need to use `m12`.

**Comment by Toflar** [comment]
I have no clue, I use `m12` when it looks shit without `m12` 🤣 But if what you're saying is true, it could probably all be automated.

**Comment by fritzmg** [comment]
> But if what you're saying is true, it could probably all be automated.

Not with the current back end CSS. See also https://github.com/contao/contao/pull/2053

**Comment by aschempp** [comment]
Closing this as the current view is intended.

**Pull request closed without merging**
