### PR TITLE
Fix array access warnings in templates

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes the following warning(s):

```
ErrorException:
Warning: Undefined array key "hasLink"

  at vendor\terminal42\contao-pageimage\contao\templates\mod_pageimage.html5:6
  at include('vendor\\terminal42\\contao-pageimage\\contao\\templates\\mod_pageimage.html5')
     (vendor\contao\core-bundle\src\Resources\contao\library\Contao\TemplateInheritance.php:108)
```

### CODE REVIEW

**Comment by aschempp** [comment]
Looking at the code base, `hasLink` will never be set because it is part of PageImage data but the template only receives data from the figure builder. So maybe we should change that to check for `href` instead and drop `hasLink`?

**Comment by contaoacademy** [comment]
I have the same problem with my installation. I would be pleased if it could be fixed.

**Comment by fritzmg** [comment]
@contaoacademy can you verify that changing

```php
if ($image['hasLink']):
```

to

```php
if ($image['href'] ?? null):
```

works as intended?

**Comment by contaoacademy** [comment]
Yes, this worked for me.

**Comment by contaoacademy** [comment]
The error message has disappeared.
However, a link was not displayed.
But I get:
`Warning: Undefined array key "title"`

**Comment by contaoacademy** [comment]
Ok, to clarify
I've now run a few more tests.

If I remove the title in the template as a test, I get an output.

To do this, the link must be set via the file manager. If I use the "Overwrite metadata" function, no link is output.

**Comment by aschempp** [comment]
any updates on the topic? 🙃

**Comment by fritzmg** [comment]
I did not have time to look into it further unfortunately.

**Comment by aschempp** [comment]
Fixed in dd9480a5ccf96cde8b9bee2a0f98037fb7ed81bc

**Pull request closed without merging**
